### PR TITLE
[BUG]Fixed compilation error issues with Linux

### PR DESCRIPTION
**Pull request by ewail**
Compiled successfully under gcc7
eg: error: 'char_traits' was not declared in this scope

### CODE REVIEW

**Comment by ewail** [comment]
Download: [Link](https://raw.githubusercontent.com/ewail/DiaNN/master/diann-linux)

**Comment by vdemichev** [comment]
Hi ewail, thank you for spotting this. Why #undef MSTOOLKIT (line 41)? Does it fail to compile with MSTOOLKIT defined?

**Comment by ewail** [comment]
> Hi ewail, thank you for spotting this. Why #undef MSTOOLKIT (line 41)? Does it fail to compile with MSTOOLKIT defined?

Need to modify the linux-build-gcc-7 script next version

error:
src/diann.cpp:73:10: fatal error: MSReader.h: No such file or directory
 #include "MSReader.h"

**Comment by ewail** [comment]
> Hi ewail, thank you for spotting this. Why #undef MSTOOLKIT (line 41)? Does it fail to compile with MSTOOLKIT defined?

for test, uncomment "//#undef MSTOOLKIT"

OK, I alrady modify the previous test section, added comment "//#undef MSTOOLKIT"

Download: [Update Link](https://github.com/ewail/DiaNN/blob/master/diann-linux)

**Pull request merged**
