### PR TITLE
prevent "goto report;" from jumping forward over declaration statements

### PR DESCRIPTION
**Pull request by guoci**
GCC 9 fails to compile this file as it conforms to the required restrictions on the `goto` statement.

### CODE REVIEW

**Comment by vdemichev** [comment]
Thanks! Do you think it would be possible to make it compile as is by just using -Wno-jump-misses-init?

**Comment by guoci** [comment]
no
```
cc1plus: warning: command line option ‘-Wno-jump-misses-init’ is valid for C/ObjC but not for C++
../src/diann.cpp: In member function ‘void Run::process(std::vector<QuantEntry>*, float)’:
../src/diann.cpp:8155:2: error: jump to label ‘report’
 8155 |  report:
      |  ^~~~~~
../src/diann.cpp:7957:23: note:   from here
 7957 |   if (QuantOnly) goto report;
      |                       ^~~~~~
../src/diann.cpp:8079:49: note:   crosses initialization of ‘int switched’
 8079 |   int processed_batches = curr_batch, fail = 0, switched = 0;
      |                                                 ^~~~~~~~
../src/diann.cpp:8079:39: note:   crosses initialization of ‘int fail’
 8079 |   int processed_batches = curr_batch, fail = 0, switched = 0;
      |                                       ^~~~
../src/diann.cpp:8079:7: note:   crosses initialization of ‘int processed_batches’
 8079 |   int processed_batches = curr_batch, fail = 0, switched = 0;
      |       ^~~~~~~~~~~~~~~~~
../src/diann.cpp:7962:7: note:   crosses initialization of ‘int start_batch’
 7962 |   int start_batch = 0;
      |       ^~~~~~~~~~~
../src/diann.cpp:7961:8: note:   crosses initialization of ‘bool do_calibrate’
 7961 |   bool do_calibrate = do_reset || RTWindowedSearch;
      |        ^~~~~~~~~~~~
../src/diann.cpp:7960:8: note:   crosses initialization of ‘bool do_reset’
 7960 |   bool do_reset = (InferWindow && !window_calculated) || recalibrate;
      |        ^~~~~~~~
make: *** [Makefile:30: all] Error 1
```

**Comment by vdemichev** [comment]
Just to confirm, you are using the makefile provided int he /mstoolkit folder?

**Comment by guoci** [comment]
@vdemichev yes, added `-Wno-jump-misses-init` to `mstoolkit/Makefile`.

**Comment by vdemichev** [comment]
Should be fixed now, thanks again for making me aware of this!

**Pull request closed without merging**
